#pragma once
#include "Course.hpp"
#include "Student.hpp"
#include "Teacher.hpp"
#include <vector>
#include <Windows.h>
#include <iomanip>
bool InputStudentInfo();
bool InputTeacherInfo();
bool InputAllInfo();
bool AllInfoTable();
bool AppendPeople();
bool RemoveStorTc();
bool Sort();
void CourseAboutTable();
void InputCourseInfo();
bool StudentsTable();
bool CheckAge();
void TeachersTable();
void CalcCourse();
void LocalInformation();